In [1]:
import pandas as pd
import warnings
warnings.filterwarnings("ignore")
dataset = pd.read_csv('50_Startups.csv')
dataset

    R&D Spend  Administration  Marketing Spend       State     Profit
0   165349.20       136897.80        471784.10    New York  192261.83
1   162597.70       151377.59        443898.53  California  191792.06
2   153441.51       101145.55        407934.54     Florida  191050.39
3   144372.41       118671.85        383199.62    New York  182901.99
4   142107.34        91391.77        366168.42     Florida  166187.94
5   131876.90        99814.71        362861.36    New York  156991.12
6   134615.46       147198.87        127716.82  California  156122.51
7   130298.13       145530.06        323876.68     Florida  155752.60
8   120542.52       148718.95        311613.29    New York  152211.77
9   123334.88       108679.17        304981.62  California  149759.96
10  101913.08       110594.11        229160.95     Florida  146121.95
11  100671.96        91790.61        249744.55  California  144259.40
12   93863.75       127320.38        249839.44     Florida  141585.52
13   91992.39       135495.07        252664.93  California  134307.35
14  119943.24       156547.42        256512.92     Florida  132602.65
15  114523.61       122616.84        261776.23    New York  129917.04
16   78013.11       121597.55        264346.06  California  126992.93
17   94657.16       145077.58        282574.31    New York  125370.37
18   91749.16       114175.79        294919.57     Florida  124266.90
19   86419.70       153514.11             0.00    New York  122776.86
20   76253.86       113867.30        298664.47  California  118474.03
21   78389.47       153773.43        299737.29    New York  111313.02
22   73994.56       122782.75        303319.26     Florida  110352.25
23   67532.53       105751.03        304768.73     Florida  108733.99
24   77044.01        99281.34        140574.81    New York  108552.04
25   64664.71       139553.16        137962.62  California  107404.34
26   75328.87       144135.98        134050.07     Florida  105733.54
27   72107.60       127864.55        353183.81    New York  105008.31
28   66051.52       182645.56        118148.20     Florida  103282.38
29   65605.48       153032.06        107138.38    New York  101004.64
30   61994.48       115641.28         91131.24     Florida   99937.59
31   61136.38       152701.92         88218.23    New York   97483.56
32   63408.86       129219.61         46085.25  California   97427.84
33   55493.95       103057.49        214634.81     Florida   96778.92
34   46426.07       157693.92        210797.67  California   96712.80
35   46014.02        85047.44        205517.64    New York   96479.51
36   28663.76       127056.21        201126.82     Florida   90708.19
37   44069.95        51283.14        197029.42  California   89949.14
38   20229.59        65947.93        185265.10    New York   81229.06
39   38558.51        82982.09        174999.30  California   81005.76
40   28754.33       118546.05        172795.67  California   78239.91
41   27892.92        84710.77        164470.71     Florida   77798.83
42   23640.93        96189.63        148001.11  California   71498.49
43   15505.73       127382.30         35534.17    New York   69758.98
44   22177.74       154806.14         28334.72  California   65200.33
45    1000.23       124153.04          1903.93    New York   64926.08
46    1315.46       115816.21        297114.46     Florida   49490.75
47       0.00       135426.92             0.00  California   42559.73
48     542.05        51743.15             0.00    New York   35673.41
49       0.00       116983.80         45173.06  California   14681.40

In [3]:
dataset = pd.get_dummies(dataset,dtype=int,drop_first=True)
dataset.columns
independent = dataset[['R&D Spend', 'Administration', 'Marketing Spend','State_Florida', 'State_New York' ]]
independent
dependent = dataset[['Profit']]
dependent

       Profit
0   192261.83
1   191792.06
2   191050.39
3   182901.99
4   166187.94
5   156991.12
6   156122.51
7   155752.60
8   152211.77
9   149759.96
10  146121.95
11  144259.40
12  141585.52
13  134307.35
14  132602.65
15  129917.04
16  126992.93
17  125370.37
18  124266.90
19  122776.86
20  118474.03
21  111313.02
22  110352.25
23  108733.99
24  108552.04
25  107404.34
26  105733.54
27  105008.31
28  103282.38
29  101004.64
30   99937.59
31   97483.56
32   97427.84
33   96778.92
34   96712.80
35   96479.51
36   90708.19
37   89949.14
38   81229.06
39   81005.76
40   78239.91
41   77798.83
42   71498.49
43   69758.98
44   65200.33
45   64926.08
46   49490.75
47   42559.73
48   35673.41
49   14681.40

In [4]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(independent,dependent,test_size =0.3,random_state =0)

In [5]:
# standarised method
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)
x_train

scy = StandardScaler()
y_train = scy.fit_transform(y_train)
y_test = scy.transform(y_test)
y_test

array([[-0.16141583],
       [ 0.79125539],
       [ 0.83455765],
       [-0.75388069],
       [ 1.87909509],
       [-0.12128983],
       [-0.67413157],
       [-0.2962321 ],
       [ 0.00295097],
       [ 1.30107013],
       [-0.31261421],
       [-0.31957517],
       [-0.10442902],
       [-0.31415143],
       [ 0.32645147]])

In [6]:
# cv method
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVR

param_grid ={'kernel':['rdf','poly','sigmoid','linear'],'C':[10,100,1000,2000,3000],'gamma':['auto','scale']}

grid = GridSearchCV(SVR(),param_grid,refit=True,verbose =3,n_jobs=-1)
grid.fit(x_train,y_train)
grid

Fitting 5 folds for each of 40 candidates, totalling 200 fits

GridSearchCV(estimator=SVR(), n_jobs=-1,
             param_grid={'C': [10, 100, 1000, 2000, 3000],
                         'gamma': ['auto', 'scale'],
                         'kernel': ['rdf', 'poly', 'sigmoid', 'linear']},
             verbose=3)

In [7]:
print(grid.best_params_)

{'C': 100, 'gamma': 'auto', 'kernel': 'linear'}

In [8]:
re = grid.cv_results_
re
table=pd.DataFrame.from_dict(re)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_gamma,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.002185,0.000665,0.000000,0.000000,10,auto,rdf,"{'C': 10, 'gamma': 'auto', 'kernel': 'rdf'}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,31
1,0.006855,0.002952,0.004100,0.001249,10,auto,poly,"{'C': 10, 'gamma': 'auto', 'kernel': 'poly'}",-9.640903e-01,8.945918e-01,0.730909,3.806707e-01,0.572856,3.229875e-01,6.656519e-01,12
2,0.005045,0.001112,0.003963,0.000907,10,auto,sigmoid,"{'C': 10, 'gamma': 'auto', 'kernel': 'sigmoid'}",-2.137841e+01,-1.053629e+01,-7.083174,-6.473032e+01,-1.885680,-2.112277e+01,2.271974e+01,22
3,0.016180,0.003476,0.004000,0.000621,10,auto,linear,"{'C': 10, 'gamma': 'auto', 'kernel': 'linear'}",8.585589e-01,9.473769e-01,0.919079,8.318672e-01,0.952253,9.018271e-01,4.833572e-02,3
4,0.002336,0.001067,0.000000,0.000000,10,scale,rdf,"{'C': 10, 'gamma': 'scale', 'kernel': 'rdf'}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,31
5,0.006121,0.000323,0.003749,0.000509,10,scale,poly,"{'C': 10, 'gamma': 'scale', 'kernel': 'poly'}",-7.657603e-01,8.845850e-01,0.727028,4.066442e-01,0.601611,3.708215e-01,5.894406e-01,11
6,0.005454,0.001547,0.003272,0.000603,10,scale,sigmoid,"{'C': 10, 'gamma': 'scale', 'kernel': 'sigmoid'}",-1.473106e+01,-4.940095e+00,-6.147813,-6.678368e+01,-2.415308,-1.900359e+01,2.424630e+01,21
7,0.012487,0.002489,0.003229,0.000470,10,scale,linear,"{'C': 10, 'gamma': 'scale', 'kernel': 'linear'}",8.585589e-01,9.473769e-01,0.919079,8.318672e-01,0.952253,9.018271e-01,4.833572e-02,3
8,0.001533,0.000231,0.000000,0.000000,100,auto,rdf,"{'C': 100, 'gamma': 'auto', 'kernel': 'rdf'}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,31
9,0.007807,0.002413,0.003049,0.000689,100,auto,poly,"{'C': 100, 'gamma': 'auto', 'kernel': 'poly'}",-1.163642e+00,7.934828e-01,0.747542,4.450937e-01,0.719070,3.083092e-01,7.459751e-01,13
10,0.003733,0.000427,0.002565,0.000434,100,auto,sigmoid,"{'C': 100, 'gamma': 'auto', 'kernel': 'sigmoid'}",-1.794487e+03,-8.194267e+02,-776.937106,-6.863890e+03,-287.671810,-2.108483e+03,2.427448e+03,23
11,0.096141,0.035113,0.002703,0.000406,100,auto,linear,"{'C': 100, 'gamma': 'auto', 'kernel': 'linear'}",8.587234e-01,9.473916e-01,0.919049,8.318925e-01,0.952098,9.018307e-01,4.826718e-02,1
12,0.001289,0.000304,0.000000,0.000000,100,scale,rdf,"{'C': 100, 'gamma': 'scale', 'kernel': 'rdf'}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,31
13,0.008013,0.001621,0.002857,0.000386,100,scale,poly,"{'C': 100, 'gamma': 'scale', 'kernel': 'poly'}",-1.164569e+00,7.935492e-01,0.747362,4.449175e-01,0.719037,3.080594e-01,7.463182e-01,17
14,0.005135,0.003058,0.004358,0.003252,100,scale,sigmoid,"{'C': 100, 'gamma': 'scale', 'kernel': 'sigmoid'}",-2.827041e+03,-7.899832e+02,-480.978939,-7.582664e+03,-350.971684,-2.406328e+03,2.739178e+03,24
15,0.104258,0.035934,0.003802,0.002468,100,scale,linear,"{'C': 100, 'gamma': 'scale', 'kernel': 'linear'}",8.587234e-01,9.473916e-01,0.919049,8.318925e-01,0.952098,9.018307e-01,4.826718e-02,1
16,0.001560,0.000611,0.000000,0.000000,1000,auto,rdf,"{'C': 1000, 'gamma': 'auto', 'kernel': 'rdf'}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,31
17,0.008313,0.003430,0.002377,0.000252,1000,auto,poly,"{'C': 1000, 'gamma': 'auto', 'kernel': 'poly'}",-1.163642e+00,7.934828e-01,0.747542,4.450937e-01,0.719070,3.083092e-01,7.459751e-01,13
18,0.003291,0.000435,0.002543,0.000332,1000,auto,sigmoid,"{'C': 1000, 'gamma': 'auto', 'kernel': 'sigmoid'}",-6.900843e+04,-3.012703e+05,-78317.353754,-6.830377e+05,-42203.727908,-2.347675e+05,2.426530e+05,25
19,1.136399,0.418401,0.003102,0.001282,1000,auto,linear,"{'C': 1000, 'gamma': 'auto', 'kernel': 'linear'}",8.577028e-01,9.472091e-01,0.919093,8.320546e-01,0.952139,9.016396e-01,4.838160e-02,5
20,0.001526,0.000304,0.000000,0.000000,1000,scale,rdf,"{'C': 1000, 'gamma': 'scale', 'kernel': 'rdf'}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,31
21,0.008288,0.002885,0.002750,0.000456,1000,scale,poly,"{'C': 1000, 'gamma': 'scale', 'kernel': 'poly'}",-1.164569e+00,7.935492e-01,0.747362,4.449175e-01,0.719037,3.080594e-01,7.463182e-01,17
22,0.004053,0.000117,0.002449,0.000383,1000,scale,sigmoid,"{'C': 1000, 'gamma': 'scale', 'kernel': 'sigmo...",-2.764250e+05,-8.242957e+04,-46253.197426,-7.544496e+05,-44669.296887,-2.408453e+05,2.707404e+05,26
23,1.133970,0.440681,0.002375,0.000221,1000,scale,linear,"{'C': 1000, 'gamma': 'scale', 'kernel': 'linear'}",8.577028e-01,9.472091e-01,0.919093,8.320546e-01,0.952139,9.016396e-01,4.838160e-02,5
24,0.001203,0.000419,0.000000,0.000000,2000,auto,rdf,"{'C': 2000, 'gamma': 'auto', 'kernel': 'rdf'}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,31
25,0.007127,0.002854,0.002791,0.001087,2000,auto,poly,"{'C': 2000, 'gamma': 'auto', 'kernel': 'poly'}",-1.163642e+00,7.934828e-01,0.747542,4.450937e-01,0.719070,3.083092e-01,7.459751e-01,13
26,0.003560,0.000290,0.003557,0.001478,2000,auto,sigmoid,"{'C': 2000, 'gamma': 'auto', 'kernel': 'sigmoid'}",-2.783104e+05,-1.202611e+06,-313404.023070,-2.731369e+06,-169222.385570,-9.389834e+05,9.697955e+05,27
27,2.381094,1.149910,0.002483,0.000216,2000,auto,linear,"{'C': 2000, 'gamma': 'auto', 'kernel': 'linear'}",8.580990e-01,9.468914e-01,0.919062,8.320946e-01,0.952031,9.016357e-01,4.821385e-02,7
28,0.001538,0.000393,0.000000,0.000000,2000,scale,rdf,"{'C': 2000, 'gamma': 'scale', 'kernel': 'rdf'}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,31
29,0.009050,0.004933,0.002423,0.000211,2000,scale,poly,"{'C': 2000, 'gamma': 'scale', 'kernel': 'poly'}",-1.164569e+00,7.935492e-01,0.747362,4.449175e-01,0.719037,3.080594e-01,7.463182e-01,17
30,0.004627,0.001826,0.002547,0.000337,2000,scale,sigmoid,"{'C': 2000, 'gamma': 'scale', 'kernel': 'sigmo...",-1.103966e+06,-3.304786e+05,-184592.369361,-3.016958e+06,-179039.983974,-9.630069e+05,1.082516e+06,28
31,2.291855,1.089653,0.002573,0.000317,2000,scale,linear,"{'C': 2000, 'gamma': 'scale', 'kernel': 'linear'}",8.580990e-01,9.468914e-01,0.919062,8.320946e-01,0.952031,9.016357e-01,4.821385e-02,7
32,0.001544,0.000485,0.000000,0.000000,3000,auto,rdf,"{'C': 3000, 'gamma': 'auto', 'kernel': 'rdf'}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,31
33,0.009445,0.003025,0.002433,0.000508,3000,auto,poly,"{'C': 3000, 'gamma': 'auto', 'kernel': 'poly'}",-1.163642e+00,7.934828e-01,0.747542,4.450937e-01,0.719070,3.083092e-01,7.459751e-01,13
34,0.003676,0.000402,0.003001,0.001075,3000,auto,sigmoid,"{'C': 3000, 'gamma': 'auto', 'kernel': 'sigmoid'}",-6.279135e+05,-2.704025e+06,-705259.887229,-6.145001e+06,-381054.831177,-2.112651e+06,2.181430e+06,29
35,3.313365,1.265594,0.002572,0.000445,3000,auto,linear,"{'C': 3000, 'gamma': 'auto', 'kernel': 'linear'}",8.576578e-01,9.465100e-01,0.919230,8.321948e-01,0.952110,9.015404e-01,4.822229e-02,9
36,0.001343,0.000569,0.000000,0.000000,3000,scale,rdf,"{'C': 3000, 'gamma': 'scale', 'kernel': 'rdf'}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,31
37,0.008472,0.002877,0.002895,0.001330,3000,scale,poly,"{'C': 3000, 'gamma': 'scale', 'kernel': 'poly'}",-1.164569e+00,7.935492e-01,0.747362,4.449175e-01,0.719037,3.080594e-01,7.463182e-01,17
38,0.003579,0.000218,0.002434,0.000344,3000,scale,sigmoid,"{'C': 3000, 'gamma': 'scale', 'kernel': 'sigmo...",-2.482622e+06,-7.441459e+05,-415016.947899,-6.787513e+06,-403111.551735,-2.166482e+06,2.435324e+06,30
39,3.169901,1.058155,0.002381,0.000608,3000,scale,linear,"{'C': 3000, 'gamma': 'scale', 'kernel': 'linear'}",8.576578e-01,9.465100e-01,0.919230,8.321948e-01,0.952110,9.015404e-01,4.822229e-02,9

In [9]:
from sklearn.metrics import r2_score

y_pred = grid.predict(x_test)
r_score=r2_score(y_test, y_pred)
print("R2 Score:", r2_score(y_test, y_pred))

R2 Score: 0.937500502733674

In [10]:
user_age = float(input("Enter Age: "))
user_bmi = float(input("Enter BMI: "))
user_children = float(input("Enter Number of Children: "))
user_sex = float(
    input("Enter Sex (1 for Male, 0 for Female): ")
)  # Male = 1, Female = 0
user_smoker = float(
    input("Enter Smoker (1 for Yes, 0 for No): ")
)

Enter Age:  60
Enter BMI:  56.89
Enter Number of Children:  6
Enter Sex (1 for Male, 0 for Female):  1
Enter Smoker (1 for Yes, 0 for No):  0

In [11]:
import pickle
# 5. Save all 3 required files using pickle
pickle.dump(grid, open('cv_model.sav', 'wb'))
pickle.dump(sc, open('scaler_x.sav', 'wb'))
pickle.dump(scy, open('scaler_y.sav', 'wb'))
# 1. Load saved model and scalers
loaded_model = pickle.load(open('cv_model.sav', 'rb'))
loaded_sc = pickle.load(open('scaler_x.sav', 'rb'))
loaded_scy = pickle.load(open('scaler_y.sav', 'rb'))

In [12]:
# 3. Transform inputs using loaded feature scaler
user_data = [[
    user_age,
    user_bmi,
    user_children,
    user_sex,
    user_smoker,
]]
scaled_input = loaded_sc.transform(user_data)

# 4. Predict scaled output
scaled_pred = loaded_model.predict(scaled_input)

# 5. Inverse transform prediction back to original scale (Profit in $)
# .reshape(-1, 1) converts 1D output back to 2D for inverse_transform
final_profit = loaded_scy.inverse_transform(scaled_pred.reshape(-1, 1))
final_profit
# print(f'\nPredicted Profit: ${final_profit[0][0]:,.2f}')

array([[45336.29085524]])