In [1]:
import pandas as pd
dataset = pd.read_csv('insurance_pre.csv')
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [2]:
dataset = pd.get_dummies(dataset,dtype=int,drop_first =True)
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [3]:
independent = dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]
dependent = dataset[['charges']]
independent
dependent

          charges
0     16884.92400
1      1725.55230
2      4449.46200
3     21984.47061
4      3866.85520
...           ...
1333  10600.54830
1334   2205.98080
1335   1629.83350
1336   2007.94500
1337  29141.36030

[1338 rows x 1 columns]

In [4]:
#  split the train and test
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(independent,dependent,test_size = 0.3,random_state=0)

In [5]:
# standarised method
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)
x_train

array([[-1.5330973 , -0.40713453, -0.89833872, -0.97676557, -0.50466988],
       [-0.03364163,  0.32855417, -0.89833872, -0.97676557, -0.50466988],
       [ 0.89459283,  2.56690911,  3.25603402, -0.97676557, -0.50466988],
       ...,
       [ 0.03776102, -0.91016269, -0.89833872,  1.02378711, -0.50466988],
       [-1.46169465,  0.76659782, -0.89833872,  1.02378711, -0.50466988],
       [-0.46205754, -1.96596021, -0.06746417, -0.97676557, -0.50466988]],
      shape=(936, 5))

In [7]:
# cv method
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVR

param_grid ={'kernel':['rdf','poly','sigmoid','linear'],'C':[10,100,1000,2000,3000],'gamma':['auto','scale']}

grid = GridSearchCV(SVR(),param_grid,refit=True,verbose =3,n_jobs=-1)
grid.fit(x_train,y_train)

Fitting 5 folds for each of 40 candidates, totalling 200 fits

C:\Anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:489: FitFailedWarning:
50 fits failed out of a total of 200.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
6 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 851, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Anaconda3\Lib\site-packages\sklearn\base.py", line 1393, in wrapper
    estimator._validate_params()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Anaconda3\Lib\site-packages\sklearn\base.py", line 554, in _validate_params
    validate_parameter_constraints(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self._parameter_constraints,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.get_params(deep=False),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        caller_name=self.__class__.__name__,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
    ...<2 lines>...
    )
sklearn.utils._param_validation.InvalidParameterError: The 'kernel' parameter of SVR must be a str among {'linear', 'sigmoid', 'precomputed', 'poly', 'rbf'} or a callable. Got 'rdf' instead.

--------------------------------------------------------------------------------
8 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 851, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Anaconda3\Lib\site-packages\sklearn\base.py", line 1393, in wrapper
    estimator._validate_params()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Anaconda3\Lib\site-packages\sklearn\base.py", line 554, in _validate_params
    validate_parameter_constraints(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self._parameter_constraints,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.get_params(deep=False),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        caller_name=self.__class__.__name__,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
    ...<2 lines>...
    )
sklearn.utils._param_validation.InvalidParameterError: The 'kernel' parameter of SVR must be a str among {'precomputed', 'poly', 'sigmoid', 'linear', 'rbf'} or a callable. Got 'rdf' instead.

--------------------------------------------------------------------------------
6 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 851, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Anaconda3\Lib\site-packages\sklearn\base.py", line 1393, in wrapper
    estimator._validate_params()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Anaconda3\Lib\site-packages\sklearn\base.py", line 554, in _validate_params
    validate_parameter_constraints(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self._parameter_constraints,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.get_params(deep=False),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        caller_name=self.__class__.__name__,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
    ...<2 lines>...
    )
sklearn.utils._param_validation.InvalidParameterError: The 'kernel' parameter of SVR must be a str among {'linear', 'sigmoid', 'poly', 'precomputed', 'rbf'} or a callable. Got 'rdf' instead.

--------------------------------------------------------------------------------
4 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 851, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Anaconda3\Lib\site-packages\sklearn\base.py", line 1393, in wrapper
    estimator._validate_params()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Anaconda3\Lib\site-packages\sklearn\base.py", line 554, in _validate_params
    validate_parameter_constraints(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self._parameter_constraints,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.get_params(deep=False),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        caller_name=self.__class__.__name__,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
    ...<2 lines>...
    )
sklearn.utils._param_validation.InvalidParameterError: The 'kernel' parameter of SVR must be a str among {'linear', 'precomputed', 'rbf', 'poly', 'sigmoid'} or a callable. Got 'rdf' instead.

--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 851, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Anaconda3\Lib\site-packages\sklearn\base.py", line 1393, in wrapper
    estimator._validate_params()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Anaconda3\Lib\site-packages\sklearn\base.py", line 554, in _validate_params
    validate_parameter_constraints(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self._parameter_constraints,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.get_params(deep=False),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        caller_name=self.__class__.__name__,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
    ...<2 lines>...
    )
sklearn.utils._param_validation.InvalidParameterError: The 'kernel' parameter of SVR must be a str among {'precomputed', 'linear', 'poly', 'rbf', 'sigmoid'} or a callable. Got 'rdf' instead.

--------------------------------------------------------------------------------
6 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 851, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Anaconda3\Lib\site-packages\sklearn\base.py", line 1393, in wrapper
    estimator._validate_params()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Anaconda3\Lib\site-packages\sklearn\base.py", line 554, in _validate_params
    validate_parameter_constraints(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self._parameter_constraints,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.get_params(deep=False),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        caller_name=self.__class__.__name__,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
    ...<2 lines>...
    )
sklearn.utils._param_validation.InvalidParameterError: The 'kernel' parameter of SVR must be a str among {'rbf', 'linear', 'precomputed', 'poly', 'sigmoid'} or a callable. Got 'rdf' instead.

--------------------------------------------------------------------------------
9 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 851, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Anaconda3\Lib\site-packages\sklearn\base.py", line 1393, in wrapper
    estimator._validate_params()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Anaconda3\Lib\site-packages\sklearn\base.py", line 554, in _validate_params
    validate_parameter_constraints(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self._parameter_constraints,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.get_params(deep=False),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        caller_name=self.__class__.__name__,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
    ...<2 lines>...
    )
sklearn.utils._param_validation.InvalidParameterError: The 'kernel' parameter of SVR must be a str among {'sigmoid', 'poly', 'linear', 'precomputed', 'rbf'} or a callable. Got 'rdf' instead.

--------------------------------------------------------------------------------
6 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 851, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Anaconda3\Lib\site-packages\sklearn\base.py", line 1393, in wrapper
    estimator._validate_params()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Anaconda3\Lib\site-packages\sklearn\base.py", line 554, in _validate_params
    validate_parameter_constraints(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self._parameter_constraints,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.get_params(deep=False),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        caller_name=self.__class__.__name__,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
    ...<2 lines>...
    )
sklearn.utils._param_validation.InvalidParameterError: The 'kernel' parameter of SVR must be a str among {'precomputed', 'rbf', 'poly', 'sigmoid', 'linear'} or a callable. Got 'rdf' instead.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
C:\Anaconda3\Lib\site-packages\sklearn\model_selection\_search.py:1234: UserWarning: One or more of the test scores are non-finite: [            nan  1.10690971e-03 -1.65700582e-03  3.67568780e-01
             nan  1.18783088e-03 -1.63503920e-03  3.67568780e-01
             nan  5.10180653e-01  4.70104813e-01  5.83498250e-01
             nan  5.10154800e-01  4.70546023e-01  5.83498250e-01
             nan  7.93554645e-01  3.05470720e-01  5.94383090e-01
             nan  7.93265039e-01  3.29645399e-01  5.94383090e-01
             nan  8.05576005e-01 -4.45127213e-01  6.20052606e-01
             nan  8.05582155e-01 -3.97237956e-01  6.20052606e-01
             nan  8.06718342e-01 -1.58818786e+00  6.24749557e-01
             nan  8.06742983e-01 -1.79902498e+00  6.24749557e-01]
  warnings.warn(
C:\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

GridSearchCV(estimator=SVR(), n_jobs=-1,
             param_grid={'C': [10, 100, 1000, 2000, 3000],
                         'gamma': ['auto', 'scale'],
                         'kernel': ['rdf', 'poly', 'sigmoid', 'linear']},
             verbose=3)

In [8]:
print(grid.best_params_)

{'C': 3000, 'gamma': 'scale', 'kernel': 'poly'}

In [10]:
re = grid.cv_results_
re
table=pd.DataFrame.from_dict(re)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_gamma,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.002797,0.000222,0.000000,0.000000,10,auto,rdf,"{'C': 10, 'gamma': 'auto', 'kernel': 'rdf'}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,31
1,0.224295,0.022771,0.023727,0.002295,10,auto,poly,"{'C': 10, 'gamma': 'auto', 'kernel': 'poly'}",0.056274,0.069532,-0.045601,-0.025079,-0.049592,0.001107,0.051309,24
2,0.189080,0.052750,0.035164,0.002480,10,auto,sigmoid,"{'C': 10, 'gamma': 'auto', 'kernel': 'sigmoid'}",0.049905,0.075905,-0.046585,-0.041004,-0.046507,-0.001657,0.053391,26
3,0.105861,0.004945,0.020340,0.001763,10,auto,linear,"{'C': 10, 'gamma': 'auto', 'kernel': 'linear'}",0.377969,0.479601,0.317872,0.337979,0.324422,0.367569,0.059777,19
4,0.001913,0.000238,0.000000,0.000000,10,scale,rdf,"{'C': 10, 'gamma': 'scale', 'kernel': 'rdf'}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,31
5,0.103030,0.006655,0.023358,0.002580,10,scale,poly,"{'C': 10, 'gamma': 'scale', 'kernel': 'poly'}",0.054964,0.071297,-0.046513,-0.024157,-0.049652,0.001188,0.051594,23
6,0.141436,0.005882,0.028769,0.003205,10,scale,sigmoid,"{'C': 10, 'gamma': 'scale', 'kernel': 'sigmoid'}",0.049644,0.076323,-0.046798,-0.040824,-0.046521,-0.001635,0.053474,25
7,0.112789,0.019388,0.019739,0.002013,10,scale,linear,"{'C': 10, 'gamma': 'scale', 'kernel': 'linear'}",0.377969,0.479601,0.317872,0.337979,0.324422,0.367569,0.059777,19
8,0.001877,0.000229,0.000000,0.000000,100,auto,rdf,"{'C': 100, 'gamma': 'auto', 'kernel': 'rdf'}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,31
9,0.108322,0.005001,0.024301,0.002423,100,auto,poly,"{'C': 100, 'gamma': 'auto', 'kernel': 'poly'}",0.540643,0.575051,0.474839,0.535730,0.424640,0.510181,0.053582,15
10,0.152694,0.008049,0.028049,0.002791,100,auto,sigmoid,"{'C': 100, 'gamma': 'auto', 'kernel': 'sigmoid'}",0.478364,0.561673,0.428331,0.450454,0.431701,0.470105,0.049110,18
11,0.131277,0.007447,0.022523,0.002857,100,auto,linear,"{'C': 100, 'gamma': 'auto', 'kernel': 'linear'}",0.584474,0.655818,0.553380,0.576939,0.546881,0.583498,0.038787,13
12,0.002938,0.000987,0.000000,0.000000,100,scale,rdf,"{'C': 100, 'gamma': 'scale', 'kernel': 'rdf'}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,31
13,0.116675,0.008450,0.024181,0.004628,100,scale,poly,"{'C': 100, 'gamma': 'scale', 'kernel': 'poly'}",0.537117,0.579373,0.471840,0.537966,0.424478,0.510155,0.054955,16
14,0.146513,0.009368,0.029491,0.002952,100,scale,sigmoid,"{'C': 100, 'gamma': 'scale', 'kernel': 'sigmoid'}",0.478930,0.563200,0.427152,0.451250,0.432199,0.470546,0.049762,17
15,0.130840,0.009397,0.019521,0.000626,100,scale,linear,"{'C': 100, 'gamma': 'scale', 'kernel': 'linear'}",0.584474,0.655818,0.553380,0.576939,0.546881,0.583498,0.038787,13
16,0.002341,0.001040,0.000000,0.000000,1000,auto,rdf,"{'C': 1000, 'gamma': 'auto', 'kernel': 'rdf'}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,31
17,0.162250,0.030177,0.023119,0.003615,1000,auto,poly,"{'C': 1000, 'gamma': 'auto', 'kernel': 'poly'}",0.829631,0.802622,0.799620,0.800321,0.735580,0.793555,0.031072,5
18,0.165437,0.012420,0.038588,0.015036,1000,auto,sigmoid,"{'C': 1000, 'gamma': 'auto', 'kernel': 'sigmoid'}",0.296082,0.372281,0.216401,0.291265,0.351325,0.305471,0.054387,22
19,0.153823,0.017104,0.019565,0.001338,1000,auto,linear,"{'C': 1000, 'gamma': 'auto', 'kernel': 'linear'}",0.605304,0.588725,0.623230,0.537931,0.616726,0.594383,0.030560,11
20,0.001846,0.000234,0.000000,0.000000,1000,scale,rdf,"{'C': 1000, 'gamma': 'scale', 'kernel': 'rdf'}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,31
21,0.167269,0.034646,0.022967,0.001884,1000,scale,poly,"{'C': 1000, 'gamma': 'scale', 'kernel': 'poly'}",0.828213,0.802622,0.799348,0.800587,0.735555,0.793265,0.030757,6
22,0.163167,0.014395,0.028535,0.002394,1000,scale,sigmoid,"{'C': 1000, 'gamma': 'scale', 'kernel': 'sigmo...",0.400044,0.366097,0.242217,0.288461,0.351407,0.329645,0.056742,21
23,0.153063,0.012130,0.019630,0.001696,1000,scale,linear,"{'C': 1000, 'gamma': 'scale', 'kernel': 'linear'}",0.605304,0.588725,0.623230,0.537931,0.616726,0.594383,0.030560,11
24,0.002921,0.001602,0.000000,0.000000,2000,auto,rdf,"{'C': 2000, 'gamma': 'auto', 'kernel': 'rdf'}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,31
25,0.278921,0.050014,0.023849,0.005215,2000,auto,poly,"{'C': 2000, 'gamma': 'auto', 'kernel': 'poly'}",0.845403,0.805639,0.816733,0.805143,0.754961,0.805576,0.029233,4
26,0.158346,0.011192,0.029188,0.002709,2000,auto,sigmoid,"{'C': 2000, 'gamma': 'auto', 'kernel': 'sigmoid'}",-0.401855,-0.508082,-0.452827,-0.751013,-0.111859,-0.445127,0.205197,28
27,0.185758,0.009539,0.019638,0.001303,2000,auto,linear,"{'C': 2000, 'gamma': 'auto', 'kernel': 'linear'}",0.605277,0.583646,0.697368,0.532547,0.681425,0.620053,0.061555,9
28,0.002895,0.001363,0.000000,0.000000,2000,scale,rdf,"{'C': 2000, 'gamma': 'scale', 'kernel': 'rdf'}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,31
29,0.261324,0.027188,0.027188,0.007786,2000,scale,poly,"{'C': 2000, 'gamma': 'scale', 'kernel': 'poly'}",0.845581,0.805624,0.816612,0.805133,0.754962,0.805582,0.029272,3
30,0.148204,0.005816,0.027727,0.003381,2000,scale,sigmoid,"{'C': 2000, 'gamma': 'scale', 'kernel': 'sigmo...",-0.385658,-0.537098,-0.474912,-0.477335,-0.111187,-0.397238,0.150976,27
31,0.194416,0.015026,0.023676,0.004937,2000,scale,linear,"{'C': 2000, 'gamma': 'scale', 'kernel': 'linear'}",0.605277,0.583646,0.697368,0.532547,0.681425,0.620053,0.061555,9
32,0.002070,0.000284,0.000000,0.000000,3000,auto,rdf,"{'C': 3000, 'gamma': 'auto', 'kernel': 'rdf'}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,31
33,0.413319,0.175666,0.024661,0.005626,3000,auto,poly,"{'C': 3000, 'gamma': 'auto', 'kernel': 'poly'}",0.846775,0.805323,0.817309,0.805191,0.758994,0.806718,0.028279,2
34,0.166154,0.012956,0.029129,0.002996,3000,auto,sigmoid,"{'C': 3000, 'gamma': 'auto', 'kernel': 'sigmoid'}",-1.090896,-1.761043,-1.734344,-2.304377,-1.050280,-1.588188,0.469215,29
35,0.212674,0.011412,0.021354,0.002648,3000,auto,linear,"{'C': 3000, 'gamma': 'auto', 'kernel': 'linear'}",0.657470,0.583501,0.697875,0.529117,0.655785,0.624750,0.060379,7
36,0.002334,0.000292,0.000000,0.000000,3000,scale,rdf,"{'C': 3000, 'gamma': 'scale', 'kernel': 'rdf'}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,31
37,0.498641,0.168264,0.021130,0.009159,3000,scale,poly,"{'C': 3000, 'gamma': 'scale', 'kernel': 'poly'}",0.846874,0.805331,0.817283,0.805239,0.758988,0.806743,0.028307,1
38,0.152897,0.005422,0.027912,0.003067,3000,scale,sigmoid,"{'C': 3000, 'gamma': 'scale', 'kernel': 'sigmo...",-1.761871,-2.139307,-1.704369,-2.340839,-1.048739,-1.799025,0.443311,30
39,0.193554,0.011025,0.016666,0.002483,3000,scale,linear,"{'C': 3000, 'gamma': 'scale', 'kernel': 'linear'}",0.657470,0.583501,0.697875,0.529117,0.655785,0.624750,0.060379,7

In [13]:
user_age = float(input("Enter Age: "))
user_bmi = float(input("Enter BMI: "))
user_children = float(input("Enter Number of Children: "))
user_sex = float(
    input("Enter Sex (1 for Male, 0 for Female): ")
)  # Male = 1, Female = 0
user_smoker = float(
    input("Enter Smoker (1 for Yes, 0 for No): ")
)

Enter Age:  70
Enter BMI:  40
Enter Number of Children:  5
Enter Sex (1 for Male, 0 for Female):  1
Enter Smoker (1 for Yes, 0 for No):  0

In [14]:
result=grid.predict([[user_age,user_bmi,user_children,user_sex,user_smoker]])
result

array([66491376.2042598])