In [1]:
import pandas as pd
dataset = pd.read_csv('insurance_pre.csv')
dataset = pd.get_dummies(dataset,dtype=int,drop_first =True)
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [2]:
independent = dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]
dependent = dataset[['charges']]
independent
dependent

          charges
0     16884.92400
1      1725.55230
2      4449.46200
3     21984.47061
4      3866.85520
...           ...
1333  10600.54830
1334   2205.98080
1335   1629.83350
1336   2007.94500
1337  29141.36030

[1338 rows x 1 columns]

In [3]:
#  split the train and test
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(independent,dependent,test_size = 0.3,random_state=0)

In [ ]:
# cv method
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVR

param_grid ={'kernel':['rdf','poly','sigmoid','linear'],'C':[10,100,1000,2000,3000],'gamma':['auto','scale']}

grid = GridSearchCV(SVR(),param_grid,refit=True,verbose =3,n_jobs=-1)
grid.fit(x_train,y_train)
grid

Fitting 5 folds for each of 40 candidates, totalling 200 fits

In [ ]:
print(grid.best_params_)

In [ ]:
re = grid.cv_results_
re
table=pd.DataFrame.from_dict(re)
table

In [ ]:
user_age = float(input("Enter Age: "))
user_bmi = float(input("Enter BMI: "))
user_children = float(input("Enter Number of Children: "))
user_sex = float(
    input("Enter Sex (1 for Male, 0 for Female): ")
)  # Male = 1, Female = 0
user_smoker = float(
    input("Enter Smoker (1 for Yes, 0 for No): ")
)

In [ ]:
result=grid.predict([[user_age,user_bmi,user_children,user_sex,user_smoker]])
result